### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by cilynx** [theunraveler/taskwarrior-web#104]
The Travis-CI build is failing because `RSpec::Mocks::setup` requires an argument under `rspec` 2 (what our specs written for), but can't have an argument under `rspec` 3 (what Travis uses by default now).  Pinning `rspec` to <3 in [taskwarrior-web.gemspec](/theunraveler/taskwarrior-web/blob/master/taskwarrior-web.gemspec) winds up throwing another error because modern versions of `rake` [don't have `last_comment`](https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11).  Short term, I'm trying to sort out if we can pin `rake` effectively.  Long term, we really need to update [the specs](/theunraveler/taskwarrior-web/tree/master/spec) to support modern versions of `rspec` and `rake`.

**Comment by cilynx** [comment]
Using `rvm` to get a `ruby 2.2` environment with `rake 10.5`, I can get past the `rspec` and `rake` issues, but now I'm getting a bunch of actual test failures.  Will dig in more later on.

**Comment by Zebradil** [comment]
Do we actually need these old ruby versions? I'd like to support only the current stable releases (2.5.1 and 2.4.4 for today).

**Comment by cilynx** [comment]
We're on the same page.  That's what I was getting at when talking about updating the specs.  It appears that a lot has changed in the last few years and I figured it made the most sense to pin "old times" in order to get to a working state and then work through incremental enhancements to bring the codebase up to current expectations.

**Comment by Zebradil** [comment]
Did you try 2.4.4? It works without any errors for me (I ran it in docker, though).

**Comment by cilynx** [comment]
Using `2.4.4` and not pinning anything new in [the gemspec](/theunraveler/taskwarrior-web/blob/master/taskwarrior-web.gemspec), I don't see any issues with `rspec` or `rake`, but I'm still seeing a pile of test failures: `83 examples, 31 failures`  This is the same outcome I got with `2.2` and `rake` pinned to an older version.

Are you seeing something different?

**Comment by Zebradil** [comment]
I haven't run any test yet — just build and run the app itself.

**Comment by cilynx** [comment]
Forgot to mention this issue in #110 -- cross-linking from here.
