### ISSUE TITLE
How to open task-web to remote local machines in the same network?

### ISSUE THREAD

**Issue by hakanu** [theunraveler/taskwarrior-web#117]
Hi there,

Great tool, I have been using a lot in my desktop. However, I'd like to reach to task-web from my other LAN machines.
For example I run task-web on http://192.168.0.12:5678/
It's all good in the same machine. But I can not open the same address on the same network on another device. I tried running task-web with different flags.

Do you know how I can do that?

Thanks.

**Comment by Zebradil** [comment]
Which exactly command do you use to run task-web?

**Comment by hakanu** [comment]
I tried different flag combos of task-web however it didn't make much difference.
This is what i use currently:
`task-web --host 192.168.0.12 --env production  -F -d`

**Comment by Zebradil** [comment]
I'm not able to test it in LAN, but I'm sure you need to use `0.0.0.0`. In this case task-web will accept connections from any IPs

**Comment by hakanu** [comment]
No luck there. I have retried that doesn't work. Ultimate goal is remotely seeing task-web from outside network via port forwarding. Fw rules are set, my python servers are just able to work remotely on WAN and LAN but task-web is not. Feel like it's a webrick issue maybe?

**Comment by Zebradil** [comment]
I did it in the past. Task-web was running on a laptop and was accessible from phone in the same LAN. I'll try it tonight.

**Comment by hakanu** [comment]
Thanks looking forward to it!

**Comment by hakanu** [comment]
any update here?

**Comment by Zebradil** [comment]
Sorry, I was overwhelmed last days.
So, for me it works.
0. Didn't have taskwarrior-web installed, so run `gem install taskwarrior-web`.
1. On my laptop I ran task-web without any additional flags.
2. Find my laptop's IP in LAN: it is 192.168.0.150.
3. On my phone go to 192.168.0.150:5678.
4. Done

Maybe some firewall restrictions on your host machine?

**Comment by Zebradil** [comment]
I'm on Mac by the way, firewall is disabled in system settings.

**Comment by hakanu** [comment]
Thanks for confirming that it works out of box.

This did the trick. I'm using ubuntu subsystem in windows. 
https://www.nextofwindows.com/allow-server-running-inside-wsl-to-be-accessible-outside-windows-10-host

Now I'm able to see my tasks, yay!
