### ISSUE TITLE
Open-URI issue

### ISSUE THREAD

**Issue by danishkhan** [theunraveler/taskwarrior-web#3]
When I run `task-web` I get this error

```
/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:277:in `open_http': 500 Internal Server Error (OpenURI::HTTPError)
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:616:in `buffer_open'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:162:in `catch'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:132:in `open_uri'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:518:in `open'
from /Users/danishkhan/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/open-uri.rb:30:in `open'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/vegas-0.1.8/lib/vegas/runner.rb:142:in `port_open?'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/vegas-0.1.8/lib/vegas/runner.rb:159:in `check_for_running'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/vegas-0.1.8/lib/vegas/runner.rb:104:in `start'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/vegas-0.1.8/lib/vegas/runner.rb:77:in `initialize'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/taskwarrior-web-0.0.5/bin/task-web:9:in `new'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/gems/taskwarrior-web-0.0.5/bin/task-web:9
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/bin/task-web:19:in `load'
from /Users/danishkhan/.rvm/gems/ree-1.8.7-2011.03/bin/task-web:19
```

**Comment by adals** [comment]
i have same issue

[2017-11-12 10:46:27 +0100] Starting 'taskwarrior-web'...
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:363:in `open_http': 500 Internal Server Error  (OpenURI::HTTPError)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:741:in `buffer_open'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:212:in `block in open_loop'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:210:in `catch'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:210:in `open_loop'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:151:in `open_uri'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:721:in `open'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/open-uri.rb:35:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `port_open?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/vegas-0.1.11/lib/vegas/runner.rb:160:in `check_for_running'
	from /usr/local/lib/ruby/gems/2.4.0/gems/vegas-0.1.11/lib/vegas/runner.rb:108:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/vegas-0.1.11/lib/vegas/runner.rb:77:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/taskwarrior-web-1.1.12/bin/task-web:9:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/taskwarrior-web-1.1.12/bin/task-web:9:in `<top (required)>'
	from /usr/local/bin/task-web:23:in `load'
	from /usr/local/bin/task-web:23:in `<main>'
