### ISSUE TITLE
task-web on Mac OS X 10.8 fails to spawn process

### ISSUE THREAD

**Issue by benjaminweb** [theunraveler/taskwarrior-web#35]
% task-web 
/Users/benjaminweb/git/taskwarrior-web/taskwarrior-web.gemspec:33: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/json-1.7.5/lib/json/ext/parser.bundle: undefined class/module Encoding (ArgumentError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/json-1.7.5/lib/json/ext.rb:13
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/json-1.7.5/lib/json.rb:58
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in `require'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/taskwarrior-web-1.0.5/lib/taskwarrior-web/task.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/taskwarrior-web-1.0.5/lib/taskwarrior-web.rb:7
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/gems/taskwarrior-web-1.0.5/bin/task-web:6
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/bin/task-web:19:in`load'
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/bin/task-web:19
    from /Users/benjaminweb/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14

**Comment by cilynx** [comment]
Closing due to age / lack of engagement.
