### ISSUE TITLE
Cannot install due to compiler error

### ISSUE THREAD

**Issue by matthiasbeyer** [theunraveler/taskwarrior-web#71]
All I know:

```bash
Building native extensions.  This could take a while...
sh: warning: setlocale: LC_ALL: cannot change locale (en)
sh: warning: setlocale: LC_ALL: cannot change locale (en)
sh: warning: setlocale: LC_ALL: cannot change locale (en)
ERROR:  Error installing taskwarrior-web:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150125-5532-pv2yw5.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en)

make "DESTDIR="
compiling generator.c
In file included from /usr/include/stdio.h:27:0,
                 from /usr/include/ruby-2.2.0/ruby/defines.h:26,
                 from /usr/include/ruby-2.2.0/ruby/ruby.h:29,
                 from /usr/include/ruby-2.2.0/ruby.h:33,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function 'fbuffer_to_s':
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
Makefile:237: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/m/.gem/ruby/2.2.0/gems/json-1.7.7 for inspection.
Results logged to /home/m/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/json-1.7.7/gem_make.out
```

```bash
$  ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```
Ask me for more information if you need them.

**Comment by senchp** [comment]
Same issue with ruby 2.2. I tried rolling back to ruby 1.9.3-dev and was able to install it, but then ran into #69 (probably due to incompatibility with newer versions of taskwarrior). Bummer - I wonder how difficult these would be to tackle? Looks like the main contributers here haven't worked on it in a while.

**Comment by laomaiweng** [comment]
Same problem with ruby 2.2 here.

This is due to some double macro expansion weirdness.
It can be solved by manually fixing the culprit in `~/.gem/ruby/2.2.0/gems/json-1.7.7/ext/json/ext/fbuffer/fbuffer.h:175`:

    -    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
    +    VALUE result = rb_str_new(FBUFFER_PTR(fb), FBUFFER_LEN(fb));

Then:

    cd ~/.gem/ruby/2.2.0
    make -C gems/json-1.7.7/ext/json/ext/generator
    gem spec cache/json-1.7.7.gem --ruby > specifications/json-1.7.7.gemspec

Hope that helps.

**Comment by theunraveler** [comment]
This seems like an issue in the `json` library. Closing for now.

**Comment by Phonebox** [comment]
@laomaiweng Thank you thank you thank you! This is my first time using ruby and I don't understand anything about it, but with your answer I located the problem and fixed it with vim :) Btw, I had to manually navigate because some things weren't the same but it worked! Thanks again!!
