### ISSUE TITLE
Newest verson haven't been pushed to Rubygems.org

### ISSUE THREAD

**Issue by Oddj0b** [theunraveler/taskwarrior-web#82]
Currently it still version 1.1.11
https://rubygems.org/gems/taskwarrior-web

**Comment by mattdf** [comment]
Yep, I don't have access to that, @theunraveler does.

If he doesn't update it I'll rename the gem and make a new one.

**Comment by derekslenk** [comment]
Ping?

**Comment by theunraveler** [comment]
Done.
