### ISSUE TITLE
can we have some screenshots?

### ISSUE THREAD

**Issue by ssbarnea** [theunraveler/taskwarrior-web#97]
I think that the project homepage would really need some screenshots if is not even possible to have a sample demo page so we would know what to expect.

**Comment by carstenhag** [comment]
Bumping this (sorry), but I had just the same idea. I stumbled upon this but have no clue how it looks like, so I'm not going to bother with ruby etc.

**Comment by PCjabber** [comment]
Just FYI, I don't think screenshots are forthcoming anytime soon. theunraveler last updated the README in December 2016, indicating a lack of time to maintain the code.

**Comment by wilmardo** [comment]
@PCjabber there is a new maintainer now, see #81

**Comment by cilynx** [comment]
Screenshots have been added to the [README](/theunraveler/taskwarrior-web/blob/master/README.md).  Thank you @Zebradil for putting these together!
